[build]
  command = "cd wordle-app && npm install && npm run build && cd .. && rm -rf build && mkdir build && cp -R server/* build/ && cp -R wordle-app/build/* build/ && cd build && npm install --only=prod && cd .. && cp server/package*.json build/ && cd build && npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200