[build]
  command = "cd wordle-app && npm install && npm run build && cd ../express-server && npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200