[build]
  command = "cd wordle-app && npm install && npm run build && cd ../express-server && npm install && npm run build"
  publish = "worldle-app/public"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"